config/routes.rb
Rails.application.routes.draw do
  

  #comment
  resources :comments, only: [:create, :destroy]
  
  #participates
  resources :participates, only: [:new, :create, :edit, :update, :destroy]
  
  get 'participates/new'

  get 'participates/edit'

  #jukebox
  get 'jukebox', to: 'jukebox#index'

  #song
  resources :songs
  post '/songs/:id/follow', to: 'follows#song_follow_toggle', as: 'song_follow'
  
  #artist
  resources :artists
  post '/artists/:id/follow', to: 'follows#artist_follow_toggle', as: 'artist_follow'
  
  #user
  devise_for :users
  
  #like
  post '/articles/:id/like', to: 'likes#like_toggle', as: 'like_article'

  #article
  root to: 'articles#index'
  resources :articles
  
  #profile
  get '/my_profile' => 'profiles#show'
  #get '/my_profile', to: 'profiles#show'와 같은 말
  get '/new_profile', to:'profiles#new'  
  get '/create_profile', to: 'profiles#new'
  post '/create_profile', to: 'profiles#create'
  get '/edit_profile', to: 'profiles#edit'
  get '/update_profile', to: 'profiles#edit'
  patch '/update_profile', to: 'profiles#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  acts_as_commentable
  has_many :likes
  has_many :l_users, through: :likes, source: :user
  validates :title, presence: true, length: {minimum: 3, maximum: 100}
  validates :content, presence: true, length: {minimum: 2}
end

app/models/artist.rb
class Artist < ApplicationRecord
    mount_uploader :image, ProfileImgUploader
    acts_as_followable
    acts_as_commentable

    has_many :participates
    has_many :songs, through: :participates, source: :song
    validates :name, presence:true
    validate :image_size
    
    private
    def image_size
        if self.image.size > 5.megabyte
            errors.add(:image, '는 5mb보다 작아야한다.')
        end
    end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment
  belongs_to :commentable, :polymorphic => true
  default_scope -> { order('created_at ASC') }
  belongs_to :user
  validates :content, presence: :true, length: {minimum: 2, maximum: 200 }
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
  
end

app/models/participate.rb
class Participate < ApplicationRecord
  belongs_to :artist
  belongs_to :song
  validate :check_uniqueness
  
  private
  def check_uniqueness
    if Participate.find_by artist_id: self.artist, song: self.song
      errors.add(:artist_song, "Already Exist")
    end
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true, length: { minimum:2, maximum: 30}
  VALID_PHONE_NUMBER = /\A010([1-9]{1}[0-9]{3})([0-9]{4})\z/
  validates :mobile, presence: true, format: {with: VALID_PHONE_NUMBER}, uniqueness: true
  
end

app/models/song.rb
class Song < ApplicationRecord
    mount_uploader :cover, CoverUploader
    acts_as_followable
    acts_as_commentable
    has_many :participates
    has_many :artists, through: :participates, source: :artist
    
    validates :title, presence: true
    validates :lyric, length: { minimum: 10 }
    validate :cover_size

    private
    def cover_size
       if self.cover.size > 5.megabyte
          errors.add(:cover, 'Cover 는 5mb보다 작아야 합니다') 
       end
    end
    
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_follower
  acts_as_followable
  has_many :comments
  has_one :profile, dependent: :destroy
  has_many :articles
  has_many :likes
  has_many :l_articles, through: :likes, source: :article

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
    def create
        if Like.find_by(user: current_user, article_id: params[:id])
            Like.create!(user: current_user, article_id: params[:id])
        end
    end
    
    def destroy
        unless Like.find_by(user: current_user, article_id: params[:id])
            Like.find_by(user: current_user, article_id: params[:id]).destroy
        end
    end
    
    def like_toggle
        like=Like.find_by(user: current_user, article_id: params[:id])
        if like.nil?
            Like.create!(user: current_user, article_id: params[:id])
        else
            like.destroy
        end
        redirect_to article_url(params[:id])
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :set_profile, only: [:show, :edit, :update]
    before_action :write_profile, except: [:new, :create]
    
    def new
        redirect_to edit_profile_url if !current_user.profile.nil?
        @profile = Profile.new
    end
    
    def create
        @profile = Profile.new(profile_params)
        @profile.address = convert_address
        @profile.user = current_user
        if @profile.save
            redirect_to my_profile_url
        else
            render 'new'
        end
        
    end
    
    def show
        @user=current_user
    end
    
    def edit
    end
    
    def update
    @profile.address = convert_address
        
       if @profile.update(profile_params)
           redirect_to my_profile_url
       else
           render 'edit'
       end
    end
    
    private
    def set_profile
        @profile = current_user.profile
    end
    
    def profile_params
        params.require(:profile).permit(:name, :mobile, :birth)
    end
    
    def write_profile
        redirect_to new_profile_url if current_user.profile.nil?
    end
    
    def convert_address
        address = ''
       params[:profile][:address].each_value do |v|
           address += "#{v}/ " 
       end
       return address
    end
    
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :check_role, except: [:show]
  
  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      redirect_to song_url(@song)
    else
      render 'new'
    
    end
    #Todo
  end
  
  def index
    @songs = Song.page(params[:page]).per(10).order(title: :asc)
  end

  def show
  end

  def edit
  end
  
  def update
    if @song.update(song_params)
      redirect_to song_url(@song)
    else
      render 'edit'    
    end
      #TODO:flash msg
  end

  def destroy
    @song.destroy
    redirect_back fallback_location: songs_url
  end
  
  private
  def set_song
    @song = Song.find params[:id]
  end
  
  def song_params
    params.require(:song).permit(:title, :lyric, :cover)
  end
  
  def check_role
    case current_user.profile.role
    when 'admin', 'editor'
    else
      redirect_back(fallback_location: root_url)
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/jukebox_helper.rb
module JukeboxHelper
    def user_editable?
        if current_user.profile.role == 'admin'
            true
        elsif current_user.profile.role == 'editor'
            true
        else
            false
        end
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/participates_helper.rb
module ParticipatesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def gravatar_url(email, size)
    gravatar = Digest::MD5::hexdigest(email).downcase
    url = "http://gravatar.com/avatar/#{gravatar}.png?s=#{size}"
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/profiles/_form.html.erb
<h1>Profile</h1>

<%= bootstrap_form_for @profile, url: path do |f| %>
  <div>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :address, '주소' %>
    <div>
      <input type="text" name="profile[address][postcode]" id="sample6_postcode" placeholder="우편번호" readonly>
      <input type="button" onclick="sample6_execDaumPostcode()" value="우편번호 찾기"><br>
      <input type="text" name="profile[address][jibun]" id="sample6_address" placeholder="주소" readonly>
      <input type="text" name="profile[address][spec]" id="sample6_address2" placeholder="상세주소">
    </div>
  </div>
  <div>
    <%= f.text_field :mobile %>
  </div>
  <div>
    <%= f.date_field :birth %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

<script src="http://dmaps.daum.net/map_js_init/postcode.v2.js"></script>
<script>
  function sample6_execDaumPostcode() {
    new daum.Postcode({
      oncomplete: function(data) {
        var fullAddr = '';
        var extraAddr = '';
        if (data.userSelectedType === 'R') {
            fullAddr = data.roadAddress;
              } else {
                  fullAddr = data.jibunAddress;
              }
              if(data.userSelectedType === 'R'){
                  if(data.bname !== ''){
                      extraAddr += data.bname;
                  }
                  if(data.buildingName !== ''){
                      extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                  }
                  fullAddr += (extraAddr !== '' ? ' ('+ extraAddr +')' : '');
              }

              document.getElementById('sample6_postcode').value = data.zonecode;
              document.getElementById('sample6_address').value = fullAddr;
              document.getElementById('sample6_address2').focus();
          }
      }).open();
  }
</script>

app/views/profiles/edit.html.erb
<h1>Profile</h1>
<%= render 'form', profile: @profile, path: update_profile_path %>

app/views/profiles/new.html.erb
<h1>Profile</h1>
<%= render 'form', profile: @profile, path: create_profile_path %>

app/views/profiles/show.html.erb
<h1><%= @user.email %>님의 프로필입니다.</h1>
<%= image_tag gravatar_url(current_user.email, 40), alt: @profile.name %>
<%= link_to fa_icon('edit 2x'), edit_profile_path %>

<p><%= @profile.name %></p>
<p><%= @profile.address %></p>
<p><%= @profile.mobile %></p>
<p><%= @profile.birth %></p>

<div class="row">
  <div class="col-md-4">
    <h2>Following Songs</h2>
    <ul>
      <% @user.following_songs.each do |song| %>
        <li>
            <%= image_tag song.cover.thumb.url %>
            <%= link_to song.title, song %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="col-md-4">
    <h2>Following Artists</h2>
    <ul>
      <% @user.following_artists.each do |artist| %>
        <li>
            <%= image_tag artist.image.thumb.url %>
            <%= link_to artist.name, artist %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="col-md-4">
    <h2>My Articles</h2>
    <ul>
      <% @user.articles.each do |article| %>
        <li>
            <%= article.title %>
            <%= link_to article.title, article %>
        </li>
      <%end%>
    </ul>
  </div>
</div>