config/routes.rb
Rails.application.routes.draw do
  

  #comment
  resources :comments, only: [:create, :destroy]
  
  #participates
  resources :participates, only: [:new, :create, :edit, :update, :destroy]
  
  get 'participates/new'

  get 'participates/edit'

  #jukebox
  get 'jukebox', to: 'jukebox#index'

  #song
  resources :songs
  post '/songs/:id/follow', to: 'follows#song_follow_toggle', as: 'song_follow'
  
  #artist
  resources :artists
  post '/artists/:id/follow', to: 'follows#artist_follow_toggle', as: 'artist_follow'
  
  #user
  devise_for :users
  
  #like
  post '/articles/:id/like', to: 'likes#like_toggle', as: 'like_article'

  #article
  root to: 'articles#index'
  resources :articles
  
  #profile
  get '/my_profile' => 'profiles#show'
  #get '/my_profile', to: 'profiles#show'와 같은 말
  get '/new_profile', to:'profiles#new'  
  get '/create_profile', to: 'profiles#new'
  post '/create_profile', to: 'profiles#create'
  get '/edit_profile', to: 'profiles#edit'
  get '/update_profile', to: 'profiles#edit'
  patch '/update_profile', to: 'profiles#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  acts_as_commentable
  has_many :likes
  has_many :l_users, through: :likes, source: :user
  validates :title, presence: true, length: {minimum: 3, maximum: 100}
  validates :content, presence: true, length: {minimum: 2}
end

app/models/artist.rb
class Artist < ApplicationRecord
    mount_uploader :image, ProfileImgUploader
    acts_as_followable
    acts_as_commentable

    has_many :participates
    has_many :songs, through: :participates, source: :song
    validates :name, presence:true
    validate :image_size
    
    private
    def image_size
        if self.image.size > 5.megabyte
            errors.add(:image, '는 5mb보다 작아야한다.')
        end
    end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment
  belongs_to :commentable, :polymorphic => true
  default_scope -> { order('created_at ASC') }
  belongs_to :user
  validates :content, presence: :true, length: {minimum: 2, maximum: 200 }
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
  
end

app/models/participate.rb
class Participate < ApplicationRecord
  belongs_to :artist
  belongs_to :song
  validate :check_uniqueness
  
  private
  def check_uniqueness
    if Participate.find_by artist_id: self.artist, song: self.song
      errors.add(:artist_song, "Already Exist")
    end
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true, length: { minimum:2, maximum: 30}
  VALID_PHONE_NUMBER = /\A010([1-9]{1}[0-9]{3})([0-9]{4})\z/
  validates :mobile, presence: true, format: {with: VALID_PHONE_NUMBER}, uniqueness: true
  
end

app/models/song.rb
class Song < ApplicationRecord
    mount_uploader :cover, CoverUploader
    acts_as_followable
    acts_as_commentable
    has_many :participates
    has_many :artists, through: :participates, source: :artist
    
    validates :title, presence: true
    validates :lyric, length: { minimum: 10 }
    validate :cover_size

    private
    def cover_size
       if self.cover.size > 5.megabyte
          errors.add(:cover, 'Cover 는 5mb보다 작아야 합니다') 
       end
    end
    
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_follower
  acts_as_followable
  has_many :comments
  has_one :profile, dependent: :destroy
  has_many :articles
  has_many :likes
  has_many :l_articles, through: :likes, source: :article

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  before_action :check_role, except: [:show]
  
  def new
    @artist =  Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artist_url(@artist)
    else
      render 'new'
    end
  end
  
  def show
  end

  def index
    @artists = Artist.all
  end

  def edit
  end
  
  def update
    if @artist.update artist_params
      redirect_to artist_url(@artist)
    else
      render 'edit'
    end
  end
  
  def destroy
    @artist.destroy
  end
  
  private
  def set_artist
    @artist = Artist.find params[:id]
  end
  
  def artist_params
    params.require(:artist).permit(:name, :nationality, :image)
  end
  
  def check_role
    if current_user.profile.role == 'admin'
    elsif current_user.profile.role == 'editor'
    else
      redirect_back(fallback_location: root_url)
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
    def create
        if Like.find_by(user: current_user, article_id: params[:id])
            Like.create!(user: current_user, article_id: params[:id])
        end
    end
    
    def destroy
        unless Like.find_by(user: current_user, article_id: params[:id])
            Like.find_by(user: current_user, article_id: params[:id]).destroy
        end
    end
    
    def like_toggle
        like=Like.find_by(user: current_user, article_id: params[:id])
        if like.nil?
            Like.create!(user: current_user, article_id: params[:id])
        else
            like.destroy
        end
        redirect_to article_url(params[:id])
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :check_role, except: [:show]
  
  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      redirect_to song_url(@song)
    else
      render 'new'
    
    end
    #Todo
  end
  
  def index
    @songs = Song.page(params[:page]).per(10).order(title: :asc)
  end

  def show
  end

  def edit
  end
  
  def update
    if @song.update(song_params)
      redirect_to song_url(@song)
    else
      render 'edit'    
    end
      #TODO:flash msg
  end

  def destroy
    @song.destroy
    redirect_back fallback_location: songs_url
  end
  
  private
  def set_song
    @song = Song.find params[:id]
  end
  
  def song_params
    params.require(:song).permit(:title, :lyric, :cover)
  end
  
  def check_role
    case current_user.profile.role
    when 'admin', 'editor'
    else
      redirect_back(fallback_location: root_url)
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/jukebox_helper.rb
module JukeboxHelper
    def user_editable?
        if current_user.profile.role == 'admin'
            true
        elsif current_user.profile.role == 'editor'
            true
        else
            false
        end
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/participates_helper.rb
module ParticipatesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def gravatar_url(email, size)
    gravatar = Digest::MD5::hexdigest(email).downcase
    url = "http://gravatar.com/avatar/#{gravatar}.png?s=#{size}"
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_follow_UI.html.erb
<% if !artist.followed_by?(current_user) %>
  <%= link_to 'Follow', artist_follow_path(artist), method: :post, class: 'btn btn-primary' %>
<% else %>
  <%= link_to 'Unfollow', artist_follow_path(artist), method: :post, class: 'btn btn-secondary' %>
<% end %>

app/views/artists/_form.html.erb
<%= bootstrap_form_for artist do |f| %>
  <div>
  <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <label for="artist_nationality">nationality</label>
    <%= f.country_select :nationality, class: "form-control", priority_countries: ["KR", "US", "JP"] %>
  </div>
  <div>
    <%= f.file_field :image, accept: 'image/jpeg, image/jpg, image/gif, image/png' %>
  </div>
  <%= f.submit %>
<% end %>

<script>
$('#artist_image').on('change',function(){
    var fileName = $(this).val().replace(/^.*[\\\/]/, '');
    $(this).next('.custom-file-label').html(fileName);
})
</script>

app/views/artists/edit.html.erb
<h1>Edit Artists</h1>
<%= render 'form', artist: @artist %>

app/views/artists/index.html.erb
<h1>Artists#index</h1>
<p>Find me in app/views/artists/index.html.erb</p>

app/views/artists/new.html.erb
<h1>New Artist</h1>
<%= render 'form', artist: @artist %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<%= render 'follow_UI', artist: @artist %>
<% if user_editable? %>
  <%= link_to fa_icon('edit 2x'), edit_artist_path(@artist) %> |
  <%= link_to fa_icon('trash 2x'), artist_path(@artist), method: :delete, data: {confirm: '삭제하시겠습니까?'}%>
<% end %>
<hr />
<%= image_tag @artist.image.url, class: 'image-center' if @artist.image?  %>
<ul>
  <% @artist.songs.each do |song|  %>
    <li>
      <%= image_tag song.cover.url, style: "width: 50px" if song.cover? %>
      <%= link_to song.title, song_path(song) %>
    </li>
  <% end %>
</ul>
<%= render 'comments/form', commentable: @artist %>
<%= render 'comments/index', commentable: @artist %>

app/views/songs/_follow_UI.html.erb
<% if !song.followed_by?(current_user) %>
  <%= link_to 'Follow', song_follow_path(song), method: :post, class: 'btn btn-primary' %>
<% else %>
  <%= link_to 'Unfollow', song_follow_path(song), method: :post, class: 'btn btn-secondary' %>
<% end %>

app/views/songs/_form.html.erb
<%= bootstrap_form_for song do |f| %>
  <div>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.text_area :lyric, class: 'tinymce', rows: 15 %>
    <%= tinymce %>
  </div>
  <div>
    <%= f.file_field :cover, accept: 'image/jpeg, image/jpg, image/gif, image/png' %>
  </div>
    <%= f.submit %>
<% end %>
<script>
    $('#song_cover').on('change',function(){
        //get the file name
        var fileName = $(this).val().replace(/^.*[\\\/]/, '');
        //replace the "Choose a file" label
        $(this).next('.custom-file-label').html(fileName);
    })
</script>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>
<%= render 'form', song: @song %>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<h1>New Song</h1>
<%= render 'form', song: @song %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>
<%= render 'follow_UI', song: @song %>
<div>
  <% if user_editable? %>
    <%= link_to fa_icon('edit 2x'), edit_song_path(@song) %> |
    <%= link_to fa_icon('trash 2x'), song_path(@song), method: :delete, data: {confirm: '삭제하시겠습니까?'}%>
  <% end %>
</div>
<hr />
<ul>
  <% @song.artists.each do |artist| %>
    <li>
      <%= image_tag artist.image.thumb.url if artist.image? %>
      <%= link_to artist.name, artist_path(artist) %>
    </li>
  <%end%>
</ul>
<%= image_tag @song.cover.url, class: 'image-center' if @song.cover?  %>
<%= @song.lyric.html_safe %>
<%= render 'comments/form', commentable: @song %>
<%= render 'comments/index', commentable: @song %>