config/routes.rb
Rails.application.routes.draw do
  

  #comment
  resources :comments, only: [:create, :destroy]
  
  #participates
  resources :participates, only: [:new, :create, :edit, :update, :destroy]
  
  get 'participates/new'

  get 'participates/edit'

  #jukebox
  get 'jukebox', to: 'jukebox#index'

  #song
  resources :songs
  post '/songs/:id/follow', to: 'follows#song_follow_toggle', as: 'song_follow'
  
  #artist
  resources :artists
  post '/artists/:id/follow', to: 'follows#artist_follow_toggle', as: 'artist_follow'
  
  #user
  devise_for :users
  
  #like
  post '/articles/:id/like', to: 'likes#like_toggle', as: 'like_article'

  #article
  root to: 'articles#index'
  resources :articles
  
  #profile
  get '/my_profile' => 'profiles#show'
  #get '/my_profile', to: 'profiles#show'와 같은 말
  get '/new_profile', to:'profiles#new'  
  get '/create_profile', to: 'profiles#new'
  post '/create_profile', to: 'profiles#create'
  get '/edit_profile', to: 'profiles#edit'
  get '/update_profile', to: 'profiles#edit'
  patch '/update_profile', to: 'profiles#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  acts_as_commentable
  has_many :likes
  has_many :l_users, through: :likes, source: :user
  validates :title, presence: true, length: {minimum: 3, maximum: 100}
  validates :content, presence: true, length: {minimum: 2}
end

app/models/artist.rb
class Artist < ApplicationRecord
    mount_uploader :image, ProfileImgUploader
    acts_as_followable
    acts_as_commentable

    has_many :participates
    has_many :songs, through: :participates, source: :song
    validates :name, presence:true
    validate :image_size
    
    private
    def image_size
        if self.image.size > 5.megabyte
            errors.add(:image, '는 5mb보다 작아야한다.')
        end
    end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment
  belongs_to :commentable, :polymorphic => true
  default_scope -> { order('created_at ASC') }
  belongs_to :user
  validates :content, presence: :true, length: {minimum: 2, maximum: 200 }
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
  
end

app/models/participate.rb
class Participate < ApplicationRecord
  belongs_to :artist
  belongs_to :song
  validate :check_uniqueness
  
  private
  def check_uniqueness
    if Participate.find_by artist_id: self.artist, song: self.song
      errors.add(:artist_song, "Already Exist")
    end
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true, length: { minimum:2, maximum: 30}
  VALID_PHONE_NUMBER = /\A010([1-9]{1}[0-9]{3})([0-9]{4})\z/
  validates :mobile, presence: true, format: {with: VALID_PHONE_NUMBER}, uniqueness: true
  
end

app/models/song.rb
class Song < ApplicationRecord
    mount_uploader :cover, CoverUploader
    acts_as_followable
    acts_as_commentable
    has_many :participates
    has_many :artists, through: :participates, source: :artist
    
    validates :title, presence: true
    validates :lyric, length: { minimum: 10 }
    validate :cover_size

    private
    def cover_size
       if self.cover.size > 5.megabyte
          errors.add(:cover, 'Cover 는 5mb보다 작아야 합니다') 
       end
    end
    
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_follower
  acts_as_followable
  has_many :comments
  has_one :profile, dependent: :destroy
  has_many :articles
  has_many :likes
  has_many :l_articles, through: :likes, source: :article

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_article, only: [:show, :update, :edit, :destroy]
  before_action :check_owner, only: [:edit, :update, :destroy]
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      redirect_to article_url(@article)
    else
      render 'new'
    end
  end

  def show
    
  end
  
  def index
    @articles = Article.page(params[:page]).per(10).order(created_at: :desc)
  end
  
  def edit
    
  end
  
  def update
    if @article.update(article_params) && @article.user == current_user
      redirect_to article_url
    else
      render 'edit'
    end
  
  end
  
  def destroy
    if @article.destroy
      redirect_to articles_url
    else
      redirect_back fallback_location: article_url(@article)
    end
  end
  
  private
  def set_article
    @article = Article.find(params[:id])
  end
  
  def article_params
    params.require(:article).permit(:title, :content)
  end
  
  def check_owner
    redirect_back fallback_location: root_url if @article.user != current_user
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
    def create
        if Like.find_by(user: current_user, article_id: params[:id])
            Like.create!(user: current_user, article_id: params[:id])
        end
    end
    
    def destroy
        unless Like.find_by(user: current_user, article_id: params[:id])
            Like.find_by(user: current_user, article_id: params[:id]).destroy
        end
    end
    
    def like_toggle
        like=Like.find_by(user: current_user, article_id: params[:id])
        if like.nil?
            Like.create!(user: current_user, article_id: params[:id])
        else
            like.destroy
        end
        redirect_to article_url(params[:id])
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :check_role, except: [:show]
  
  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      redirect_to song_url(@song)
    else
      render 'new'
    
    end
    #Todo
  end
  
  def index
    @songs = Song.page(params[:page]).per(10).order(title: :asc)
  end

  def show
  end

  def edit
  end
  
  def update
    if @song.update(song_params)
      redirect_to song_url(@song)
    else
      render 'edit'    
    end
      #TODO:flash msg
  end

  def destroy
    @song.destroy
    redirect_back fallback_location: songs_url
  end
  
  private
  def set_song
    @song = Song.find params[:id]
  end
  
  def song_params
    params.require(:song).permit(:title, :lyric, :cover)
  end
  
  def check_role
    case current_user.profile.role
    when 'admin', 'editor'
    else
      redirect_back(fallback_location: root_url)
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/jukebox_helper.rb
module JukeboxHelper
    def user_editable?
        if current_user.profile.role == 'admin'
            true
        elsif current_user.profile.role == 'editor'
            true
        else
            false
        end
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/participates_helper.rb
module ParticipatesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def gravatar_url(email, size)
    gravatar = Digest::MD5::hexdigest(email).downcase
    url = "http://gravatar.com/avatar/#{gravatar}.png?s=#{size}"
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/articles/_form.html.erb
<%= bootstrap_form_for @article do |f| %>
  <div>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.text_area :content, class: 'tinymce', rows: 15 %>
    <%= tinymce %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/_like.html.erb
<% if @article.l_users.include?(current_user) %>

  <%= link_to(fa_icon('thumbs-up', style: 'color: blue'), like_article_path, method: :post) %>
<% else %>
  <%= link_to(fa_icon('thumbs-up', style: 'color: black'), like_article_path, method: :post) %>
<% end %>


<strong>
  <% if @article.likes.count > 3 %>
    <% @article.l_users.sample(3).each do |user| %>
      <%= user.profile.name %>님,
      <% end %>
      외 <%= @article.likes.count - 3 %>명이 좋아합니다.
  <% elsif @article.likes.count > 0 %>
    <% @article.l_users.each do |user| %>
    <%= user.profile.name %> 님,
    <% end %>이 좋아합니다.
  <% end %>
</strong>

app/views/articles/_userUI.html.erb
<%= image_tag gravatar_url(@article.user.email, 64), alt: @article.user.profile.name %>
<strong><%= @article.user.profile.name %></strong>

<div>
  <% if @article.user == current_user %>
    <%= link_to fa_icon('edit 2x'), edit_article_path(@article) %> |
    <%= link_to fa_icon('trash 2x'), article_path(@article), method: :delete, data: {confirm: '삭제하시겠습니까?'}%>
  <% end %>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'form', article: @article %> 

app/views/articles/index.html.erb
<h1>Articles</h1>
<%= link_to 'New article', new_article_path, class:"btn btn-primary", role:"button" %>
<hr/>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Writer</th>
      <th>likes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to "#{article.title}(#{article.comments.count})", article %></td>
        <td><%= article.user.profile.name %></td>
        <td><%= article.likes.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="center">
    <%= paginate @articles, theme: 'twitter-bootstrap-4' %>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form', article: @article %> 

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<%= render 'userUI' %>
<%= render 'like' %>
<hr />
<p> <%= @article.content.html_safe %> </p>
<%= render 'comments/form', commentable: @article %>
<%= render 'comments/index', commentable: @article %>