config/routes.rb
Rails.application.routes.draw do
  

  #comment
  resources :comments, only: [:create, :destroy]
  
  #participates
  resources :participates, only: [:new, :create, :edit, :update, :destroy]
  
  get 'participates/new'

  get 'participates/edit'

  #jukebox
  get 'jukebox', to: 'jukebox#index'

  #song
  resources :songs
  post '/songs/:id/follow', to: 'follows#song_follow_toggle', as: 'song_follow'
  
  #artist
  resources :artists
  post '/artists/:id/follow', to: 'follows#artist_follow_toggle', as: 'artist_follow'
  
  #user
  devise_for :users
  
  #like
  post '/articles/:id/like', to: 'likes#like_toggle', as: 'like_article'

  #article
  root to: 'articles#index'
  resources :articles
  
  #profile
  get '/my_profile' => 'profiles#show'
  #get '/my_profile', to: 'profiles#show'와 같은 말
  get '/new_profile', to:'profiles#new'  
  get '/create_profile', to: 'profiles#new'
  post '/create_profile', to: 'profiles#create'
  get '/edit_profile', to: 'profiles#edit'
  get '/update_profile', to: 'profiles#edit'
  patch '/update_profile', to: 'profiles#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  acts_as_commentable
  has_many :likes
  has_many :l_users, through: :likes, source: :user
  validates :title, presence: true, length: {minimum: 3, maximum: 100}
  validates :content, presence: true, length: {minimum: 2}
end

app/models/artist.rb
class Artist < ApplicationRecord
    mount_uploader :image, ProfileImgUploader
    acts_as_followable
    acts_as_commentable

    has_many :participates
    has_many :songs, through: :participates, source: :song
    validates :name, presence:true
    validate :image_size
    
    private
    def image_size
        if self.image.size > 5.megabyte
            errors.add(:image, '는 5mb보다 작아야한다.')
        end
    end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment
  belongs_to :commentable, :polymorphic => true
  default_scope -> { order('created_at ASC') }
  belongs_to :user
  validates :content, presence: :true, length: {minimum: 2, maximum: 200 }
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
  
end

app/models/participate.rb
class Participate < ApplicationRecord
  belongs_to :artist
  belongs_to :song
  validate :check_uniqueness
  
  private
  def check_uniqueness
    if Participate.find_by artist_id: self.artist, song: self.song
      errors.add(:artist_song, "Already Exist")
    end
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true, length: { minimum:2, maximum: 30}
  VALID_PHONE_NUMBER = /\A010([1-9]{1}[0-9]{3})([0-9]{4})\z/
  validates :mobile, presence: true, format: {with: VALID_PHONE_NUMBER}, uniqueness: true
  
end

app/models/song.rb
class Song < ApplicationRecord
    mount_uploader :cover, CoverUploader
    acts_as_followable
    acts_as_commentable
    has_many :participates
    has_many :artists, through: :participates, source: :artist
    
    validates :title, presence: true
    validates :lyric, length: { minimum: 10 }
    validate :cover_size

    private
    def cover_size
       if self.cover.size > 5.megabyte
          errors.add(:cover, 'Cover 는 5mb보다 작아야 합니다') 
       end
    end
    
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_follower
  acts_as_followable
  has_many :comments
  has_one :profile, dependent: :destroy
  has_many :articles
  has_many :likes
  has_many :l_articles, through: :likes, source: :article

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/jukebox_helper.rb
module JukeboxHelper
    def user_editable?
        if current_user.profile.role == 'admin'
            true
        elsif current_user.profile.role == 'editor'
            true
        else
            false
        end
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/participates_helper.rb
module ParticipatesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def gravatar_url(email, size)
    gravatar = Digest::MD5::hexdigest(email).downcase
    url = "http://gravatar.com/avatar/#{gravatar}.png?s=#{size}"
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/_footer.html.erb
 <footer class="container">
    <hr class="my-1" />
    <small>
      <a href="https://github.com/davidkunin">Kun's Github</a>
      <a href="https://likelion.net">likelion homepage</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to 'about', '#' %></li>
        <li><%= link_to 'contact', '#' %></li>
        <li><%= link_to 'log in', '#' %></li>
      </ul>
    </nav>
  </footer>

app/views/layouts/_header.html.erb
  <header class="navbar navbar-dark bg-dark navbar-expand-lg fixed-top">
    <div class="container">
      <%= link_to "KUN", "root_path", id:'logo', class: 'navbar-brand' %>
    <!--Toggle Button-->
    <button class="navbar-toggler" type="button" 
                  data-toggle="collapse"
                  data-target="#navbarNav"
                  aria-controls="navbarNav"
                  aria-expanded="false"
                  aria-label="Toogle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <!--nav bar-->
    <nav class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><%=link_to 'Home', root_path, class: 'nav-link' %></li>
        <li class="nav-item"><%=link_to 'Jukebox', jukebox_path , class: 'nav-link' %></li>
        <li class="nav-item"><%=link_to 'Articles', articles_path, class: 'nav-link' %></li>
        
        <% if user_signed_in? %>
          <li class="nav-item"><%=link_to 'My page', my_profile_path, class: 'nav-link' %></li>
        <% end %>
        <li class="nav-item">
          <%if !user_signed_in? %>
            <%=link_to 'Log in', new_user_session_path, class: 'nav-link' %>
          <% else %>
            <%=link_to 'Log out', destroy_user_session_path,
                                  method: :delete, 
                                  data: {confirm: 'Logout 하시겠습니까?'}, 
                                  class: 'nav-link' %>
          <%end%>
        </li>
          
        
      </ul>
    </nav>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Unilikelion</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%=render 'layouts/header'%>
<div class="container">
  <%= yield %>
</div>
<%= render 'layouts/footer' %>

</body>
</html>